version: "3.7"
services:
  shortener:
    image: openjdk:8-alpine
    command: java -jar shortener.jar
    build: .
    ports:
      - "8090:8090"
    volumes:
      - ./shortener-api/target/shortener-api-0.0.1-SNAPSHOT.jar:/shortener.jar